# Generated by Django 5.2.6 on 2025-09-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newscheck',
            unique_together={('text', 'state')},
        ),
        migrations.RemoveField(
            model_name='state',
            name='language_code',
        ),
        migrations.AlterField(
            model_name='newscheck',
            name='prediction_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newscheck',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.state'),
        ),
        migrations.RemoveField(
            model_name='newscheck',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='newscheck',
            name='count',
        ),
        migrations.RemoveField(
            model_name='newscheck',
            name='sources',
        ),
    ]
